### ISSUE TITLE
Use details element for accordion

### ISSUE THREAD

**Issue by rightfold** [NamPNQ/You-Dont-Need-Javascript#18]
Why not use the `details` element for the accordion instead of a hidden checkbox?

**Comment by Martin-Pitt** [comment]
@rightfold the big failure of the `details` element is the fact that they kill the layout when hiding content which means it is impossible to make animate it closing.

They are awesome that they have got native functionality, but the browsers screwed up royally by not allowing the animation to close with a CSS transition.

No transition = higher cognitive load = user wondering wtf happened when page changes _instantly_.

**Comment by rightfold** [comment]
Ah I see, thanks. :)
